blank_issues_enabled: false
contact_links:
  - name: Discussion / Questions
    url: https://github.com/FlowScale-AI/flowscale-aios/discussions

    about: Ask questions and discuss ideas in Discussions before opening an issue.
